### ISSUE TITLE
Server To-do List

### ISSUE THREAD

**Issue by Chen-Gary** [Chen-Gary/note-squared#4]
### 1. admin

- [x] 改所有user的 profile info (包括：赋予admin权限)
- [x] 改所有user的密码
- [x] user list 分页
- [ ] ~~改头像？~~

### 2. normal user

- [x] 注册 / 登录
- [x] 上传/获取 头像
  - [ ] 把原先上传的头像删掉

- [x] 改名
- [x] 改密码*2（with old password / with email）
- [ ] ~~改邮箱？~~

### 3. user schema

- [ ] ~~添加个性签名？~~

### 4. Others

- [ ] 检查Email syntax

- [ ] 检查password复杂度

- [ ] 昵称最短长度？

## 笔记部分

- [x] 编辑/新增/删除 笔记

- [x] 加folder（分类）

- 数据库查询笔记 - 结果需要分页

  * 查询结果给**所有normal user**（仅限public note）

    - [x] 笔记推荐功能（sort by time, sort by 点赞数, 其他算法？）

    - [x] 搜索功能 - 搜索所有public notes（正则匹配？）

  * 查询结果给**自己**（public + private）
    - [x] 查询自己的所有笔记，包含folder信息
    - [x] 搜索所有自己的笔记

  * 查询结果给**admin**？（public + private）
    - [x] 查询所有数据库中的笔记

- [x] fork 他人分享的笔记
- [x] 点赞？
- [ ] ~~评论~~

## 其他部分

- [x] 部署到云服务器
